-- Improve function security: set stable search_path
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql
SECURITY INVOKER
SET search_path TO 'public';

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (user_id, display_name)
  VALUES (NEW.id, NEW.raw_user_meta_data ->> 'name');
  
  INSERT INTO public.user_stats (user_id)
  VALUES (NEW.id);
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public';

-- Ensure unique questions per subject/topic/text
CREATE UNIQUE INDEX IF NOT EXISTS questions_subject_topic_question_unique
  ON public.questions (subject, topic, question);

-- Seed 4 more questions per topic so each topic has at least 5
INSERT INTO public.questions (question, options, correct_answer, explanation, subject, topic)
VALUES
-- PHYSICS
-- Mechanics
('Mechanics Q2: In uniform circular motion, centripetal acceleration is',
 '[{"label":"A","text":"v^2/r toward center"},{"label":"B","text":"v^2/r outward"},{"label":"C","text":"zero"},{"label":"D","text":"constant and outward"}]',
 'A','Always directed toward the center with magnitude v^2/r.','Physics','Mechanics'),
('Mechanics Q3: Work done by a conservative force around a closed path is',
 '[{"label":"A","text":"Zero"},{"label":"B","text":"Positive"},{"label":"C","text":"Negative"},{"label":"D","text":"Path-dependent"}]',
 'A','Closed loop work by conservative forces is zero.','Physics','Mechanics'),
('Mechanics Q4: Momentum is conserved in a system when',
 '[{"label":"A","text":"Net external force is zero"},{"label":"B","text":"Internal forces vanish"},{"label":"C","text":"Mass is constant"},{"label":"D","text":"Velocity is constant"}]',
 'A','dP/dt = F_ext; if F_ext = 0, momentum is conserved.','Physics','Mechanics'),
('Mechanics Q5: For projectile motion, maximum height is',
 '[{"label":"A","text":"u^2 sin^2(theta)/(2g)"},{"label":"B","text":"u^2/(2g)"},{"label":"C","text":"u sin(theta)/g"},{"label":"D","text":"u cos(theta)/g"}]',
 'A','Derived from vertical energy/kinematics.','Physics','Mechanics'),
-- Thermodynamics
('Thermodynamics Q2: A process at constant pressure is',
 '[{"label":"A","text":"Isobaric"},{"label":"B","text":"Isochoric"},{"label":"C","text":"Isothermal"},{"label":"D","text":"Adiabatic"}]',
 'A','Isobaric means constant pressure.','Physics','Thermodynamics'),
('Thermodynamics Q3: For an ideal gas in isothermal process, ΔU equals',
 '[{"label":"A","text":"0"},{"label":"B","text":"nRT"},{"label":"C","text":"−nRT"},{"label":"D","text":"Depends on path"}]',
 'A','Internal energy of ideal gas depends only on temperature.','Physics','Thermodynamics'),
('Thermodynamics Q4: In adiabatic expansion of ideal gas, heat exchanged is',
 '[{"label":"A","text":"0"},{"label":"B","text":"positive"},{"label":"C","text":"negative"},{"label":"D","text":"finite and nonzero"}]',
 'A','Adiabatic implies Q = 0.','Physics','Thermodynamics'),
('Thermodynamics Q5: Entropy change for a reversible process is',
 '[{"label":"A","text":"dQ_rev/T"},{"label":"B","text":"TdQ_rev"},{"label":"C","text":"−dQ_rev/T"},{"label":"D","text":"0 always"}]',
 'A','dS = δQ_rev/T.','Physics','Thermodynamics'),
-- Waves & Oscillations
('Waves Q2: For SHM, acceleration is proportional to',
 '[{"label":"A","text":"Displacement and opposite in direction"},{"label":"B","text":"Velocity"},{"label":"C","text":"Constant"},{"label":"D","text":"Square of displacement"}]',
 'A','a = −ω^2 x.','Physics','Waves & Oscillations'),
('Waves Q3: Fundamental frequency of a string fixed at both ends is',
 '[{"label":"A","text":"v/(2L)"},{"label":"B","text":"v/L"},{"label":"C","text":"2v/L"},{"label":"D","text":"v/4L"}]',
 'A','First harmonic f1 = v/(2L).','Physics','Waves & Oscillations'),
('Waves Q4: Beats occur when two waves have',
 '[{"label":"A","text":"Slightly different frequencies"},{"label":"B","text":"Same frequency"},{"label":"C","text":"Same amplitude"},{"label":"D","text":"Same phase"}]',
 'A','Beat frequency = |f1 − f2|.','Physics','Waves & Oscillations'),
('Waves Q5: Phase difference of π corresponds to',
 '[{"label":"A","text":"Antiphase"},{"label":"B","text":"In phase"},{"label":"C","text":"Quarter phase"},{"label":"D","text":"No relation"}]',
 'A','π rad means opposite phase.','Physics','Waves & Oscillations'),
-- Optics
('Optics Q2: Mirror formula for spherical mirrors is',
 '[{"label":"A","text":"1/f = 1/v + 1/u"},{"label":"B","text":"f = u+v"},{"label":"C","text":"f = uv"},{"label":"D","text":"u = v"}]',
 'A','Standard sign convention formula.','Physics','Optics'),
('Optics Q3: Refractive index n equals',
 '[{"label":"A","text":"c/v"},{"label":"B","text":"v/c"},{"label":"C","text":"cv"},{"label":"D","text":"1"}]',
 'A','n = speed in vacuum / speed in medium.','Physics','Optics'),
('Optics Q4: Total internal reflection occurs when light travels',
 '[{"label":"A","text":"From denser to rarer medium with i > critical"},{"label":"B","text":"From rarer to denser"},{"label":"C","text":"At normal incidence"},{"label":"D","text":"Always"}]',
 'A','Condition: i > ic and n1 > n2.','Physics','Optics'),
('Optics Q5: Power of a lens (in diopters) is',
 '[{"label":"A","text":"1/f (meters)"},{"label":"B","text":"f (meters)"},{"label":"C","text":"−f (meters)"},{"label":"D","text":"f (cm)"}]',
 'A','P = 1/f with f in meters.','Physics','Optics'),
-- Electricity & Magnetism
('E&M Q2: Field due to a long straight current-carrying wire at distance r is',
 '[{"label":"A","text":"μ0 I/(2πr)"},{"label":"B","text":"μ0 I r/2"},{"label":"C","text":"μ0 r/(2πI)"},{"label":"D","text":"Zero"}]',
 'A','From Biot–Savart law.','Physics','Electricity & Magnetism'),
('E&M Q3: Gauss law states the electric flux through a closed surface equals',
 '[{"label":"A","text":"Q_enclosed/ε0"},{"label":"B","text":"ε0 Q_enclosed"},{"label":"C","text":"0"},{"label":"D","text":"Q_enclosed"}]',
 'A','Φ = Q/ε0.','Physics','Electricity & Magnetism'),
('E&M Q4: For capacitors in series, equivalent capacitance is',
 '[{"label":"A","text":"(1/Ceq) = Σ(1/Ci)"},{"label":"B","text":"Ceq = ΣCi"},{"label":"C","text":"Ceq = product"},{"label":"D","text":"Zero"}]',
 'A','Series add inverses.','Physics','Electricity & Magnetism'),
('E&M Q5: Drift velocity increases when',
 '[{"label":"A","text":"Electric field increases"},{"label":"B","text":"Temperature decreases always"},{"label":"C","text":"Carrier density decreases"},{"label":"D","text":"Cross-section increases"}]',
 'A','v_d ∝ E (for given mobility).','Physics','Electricity & Magnetism'),
-- Modern Physics
('Modern Physics Q2: De Broglie wavelength λ of particle is',
 '[{"label":"A","text":"h/p"},{"label":"B","text":"hp"},{"label":"C","text":"p/h"},{"label":"D","text":"h^2/p"}]',
 'A','Matter waves: λ = h/p.','Physics','Modern Physics'),
('Modern Physics Q3: Binding energy per nucleon is a measure of',
 '[{"label":"A","text":"Nuclear stability"},{"label":"B","text":"Atomic number"},{"label":"C","text":"Isotopic mass only"},{"label":"D","text":"Electron energy"}]',
 'A','Higher BE/A implies greater stability.','Physics','Modern Physics'),
('Modern Physics Q4: In Bohr model, angular momentum is quantized as',
 '[{"label":"A","text":"mvr = n(h/2π)"},{"label":"B","text":"mvr = nh"},{"label":"C","text":"mvr = h"},{"label":"D","text":"mvr = 0"}]',
 'A','Quantization condition mvr = nħ.','Physics','Modern Physics'),
('Modern Physics Q5: Stopping potential in photoelectric effect depends on',
 '[{"label":"A","text":"Frequency of light"},{"label":"B","text":"Intensity only"},{"label":"C","text":"Work function only"},{"label":"D","text":"Area of cathode"}]',
 'A','eVs = h(f − f0).','Physics','Modern Physics'),
-- Current Electricity
('Current Electricity Q2: Resistivity of a conductor',
 '[{"label":"A","text":"Increases with temperature (generally)"},{"label":"B","text":"Decreases always with T"},{"label":"C","text":"Is zero"},{"label":"D","text":"Is infinite"}]',
 'A','For metals, ρ increases with T.','Physics','Current Electricity'),
('Current Electricity Q3: Combination giving minimum equivalent resistance is',
 '[{"label":"A","text":"Parallel"},{"label":"B","text":"Series"},{"label":"C","text":"Mixed"},{"label":"D","text":"Delta"}]',
 'A','Parallel reduces equivalent resistance.','Physics','Current Electricity'),
('Current Electricity Q4: Kirchhoff current law states',
 '[{"label":"A","text":"Sum of currents at a node is zero"},{"label":"B","text":"Sum of voltages in loop is zero"},{"label":"C","text":"Power is constant"},{"label":"D","text":"Charge is not conserved"}]',
 'A','KCL: algebraic sum equals zero.','Physics','Current Electricity'),
('Current Electricity Q5: EMF of a cell is',
 '[{"label":"A","text":"Work done per unit charge"},{"label":"B","text":"Potential difference across external load only"},{"label":"C","text":"Always equal to terminal voltage"},{"label":"D","text":"Current times resistance"}]',
 'A','EMF is energy per charge supplied by source.','Physics','Current Electricity'),
-- Electromagnetic Induction
('EMI Q2: Lenz law ensures',
 '[{"label":"A","text":"Conservation of energy"},{"label":"B","text":"Conservation of momentum"},{"label":"C","text":"Charge quantization"},{"label":"D","text":"Mass-energy equivalence"}]',
 'A','Opposes cause; energy is conserved.','Physics','Electromagnetic Induction'),
('EMI Q3: Induced emf in a coil is proportional to',
 '[{"label":"A","text":"Rate of change of magnetic flux linkage"},{"label":"B","text":"Flux only"},{"label":"C","text":"Square of turns"},{"label":"D","text":"Area squared"}]',
 'A','ε = −N dΦ/dt.','Physics','Electromagnetic Induction'),
('EMI Q4: Self-inductance depends on',
 '[{"label":"A","text":"Geometry and core material"},{"label":"B","text":"Battery used"},{"label":"C","text":"External resistance only"},{"label":"D","text":"None"}]',
 'A','L is set by coil turns, area, length, permeability.','Physics','Electromagnetic Induction'),
('EMI Q5: In a transformer, power (ideal) in primary and secondary is',
 '[{"label":"A","text":"Equal"},{"label":"B","text":"Primary greater"},{"label":"C","text":"Secondary greater"},{"label":"D","text":"Zero"}]',
 'A','Ideal transformer conserves power (neglecting losses).','Physics','Electromagnetic Induction'),
-- AC Circuits
('AC Q2: Impedance Z of series R-L circuit is',
 '[{"label":"A","text":"√(R^2 + (ωL)^2)"},{"label":"B","text":"R + ωL"},{"label":"C","text":"R − ωL"},{"label":"D","text":"R/(ωL)"}]',
 'A','Phasor addition of R and jωL.','Physics','AC Circuits'),
('AC Q3: Power factor is',
 '[{"label":"A","text":"cos φ"},{"label":"B","text":"sin φ"},{"label":"C","text":"tan φ"},{"label":"D","text":"cot φ"}]',
 'A','φ is phase between V and I.','Physics','AC Circuits'),
('AC Q4: Resonance in RLC occurs when',
 '[{"label":"A","text":"ω = 1/√(LC)"},{"label":"B","text":"ω = √(LC)"},{"label":"C","text":"ω = L/C"},{"label":"D","text":"ω = C/L"}]',
 'A','Inductive reactance equals capacitive reactance.','Physics','AC Circuits'),
('AC Q5: In pure inductive AC circuit, current',
 '[{"label":"A","text":"Lags voltage by 90°"},{"label":"B","text":"Leads by 90°"},{"label":"C","text":"In phase"},{"label":"D","text":"Opposite phase"}]',
 'A','Inductor makes current lag by π/2.','Physics','AC Circuits'),
-- Atomic Physics
('Atomic Q2: Ionization energy is the energy required to',
 '[{"label":"A","text":"Remove an electron from ground state"},{"label":"B","text":"Add a proton"},{"label":"C","text":"Break nucleus"},{"label":"D","text":"Form covalent bond"}]',
 'A','Definition of ionization energy.','Physics','Atomic Physics'),
('Atomic Q3: Hydrogen line spectra arise due to',
 '[{"label":"A","text":"Electron transitions between quantized levels"},{"label":"B","text":"Continuum emission"},{"label":"C","text":"Nuclear transitions"},{"label":"D","text":"Molecular rotation"}]',
 'A','Balmer, Lyman, etc. due to level transitions.','Physics','Atomic Physics'),
('Atomic Q4: Principal quantum number n primarily defines',
 '[{"label":"A","text":"Shell/size and energy"},{"label":"B","text":"Shape only"},{"label":"C","text":"Orientation only"},{"label":"D","text":"Spin only"}]',
 'A','n sets energy and average radius.','Physics','Atomic Physics'),
('Atomic Q5: X-rays are produced when',
 '[{"label":"A","text":"High-energy electrons decelerate in metal target"},{"label":"B","text":"Electrons at rest"},{"label":"C","text":"Nuclei fuse"},{"label":"D","text":"Atoms rotate"}]',
 'A','Bremsstrahlung and characteristic lines.','Physics','Atomic Physics'),

-- CHEMISTRY
-- Physical Chemistry
('Physical Chem Q2: Molarity is defined as',
 '[{"label":"A","text":"moles of solute per liter of solution"},{"label":"B","text":"grams per liter"},{"label":"C","text":"moles per kg solvent"},{"label":"D","text":"percent by mass"}]',
 'A','M = n/V (L).','Chemistry','Physical Chemistry'),
('Physical Chem Q3: The unit of rate constant for a first-order reaction is',
 '[{"label":"A","text":"s^-1"},{"label":"B","text":"mol L^-1 s^-1"},{"label":"C","text":"L mol^-1 s^-1"},{"label":"D","text":"dimensionless"}]',
 'A','First order has time^-1.','Chemistry','Physical Chemistry'),
('Physical Chem Q4: Colligative properties depend on',
 '[{"label":"A","text":"Number of solute particles"},{"label":"B","text":"Nature of solute"},{"label":"C","text":"Color of solute"},{"label":"D","text":"Pressure only"}]',
 'A','They depend only on particle count.','Chemistry','Physical Chemistry'),
('Physical Chem Q5: pH of a solution is',
 '[{"label":"A","text":"−log10[H+]"},{"label":"B","text":"log10[H+]"},{"label":"C","text":"1/[H+]"},{"label":"D","text":"[H+]"}]',
 'A','Definition of pH.','Chemistry','Physical Chemistry'),
-- Organic Chemistry
('Organic Q2: Functional group of alcohol is',
 '[{"label":"A","text":"−OH"},{"label":"B","text":"−CHO"},{"label":"C","text":"−COOH"},{"label":"D","text":"−NH2"}]',
 'A','Hydroxyl group.','Chemistry','Organic Chemistry'),
('Organic Q3: Markovnikov rule applies to',
 '[{"label":"A","text":"Electrophilic addition to alkenes"},{"label":"B","text":"Nucleophilic substitution"},{"label":"C","text":"Elimination only"},{"label":"D","text":"Free radical polymerization only"}]',
 'A','H adds to carbon with more H (in absence of peroxides).','Chemistry','Organic Chemistry'),
('Organic Q4: An aldehyde can be distinguished from ketone by',
 '[{"label":"A","text":"Tollen''s test (silver mirror)"},{"label":"B","text":"Baeyer test"},{"label":"C","text":"Bromine water"},{"label":"D","text":"Lassaigne test"}]',
 'A','Aldehydes give silver mirror with Tollen''s reagent.','Chemistry','Organic Chemistry'),
('Organic Q5: Aromaticity requires',
 '[{"label":"A","text":"Planar, cyclic, conjugated, 4n+2 pi electrons"},{"label":"B","text":"Planar, 4n pi"},{"label":"C","text":"Nonplanar only"},{"label":"D","text":"Saturated ring"}]',
 'A','Huckel rule for aromatic compounds.','Chemistry','Organic Chemistry'),
-- Inorganic Chemistry
('Inorganic Q2: The most electronegative element is',
 '[{"label":"A","text":"Fluorine"},{"label":"B","text":"Chlorine"},{"label":"C","text":"Oxygen"},{"label":"D","text":"Nitrogen"}]',
 'A','F has highest electronegativity.','Chemistry','Inorganic Chemistry'),
('Inorganic Q3: Coordination number in [Cu(NH3)4]2+ is',
 '[{"label":"A","text":"4"},{"label":"B","text":"2"},{"label":"C","text":"6"},{"label":"D","text":"8"}]',
 'A','Four NH3 ligands.','Chemistry','Inorganic Chemistry'),
('Inorganic Q4: Oxidation number of S in H2SO4 is',
 '[{"label":"A","text":"+6"},{"label":"B","text":"+4"},{"label":"C","text":"+2"},{"label":"D","text":"0"}]',
 'A','Balancing oxidation states.','Chemistry','Inorganic Chemistry'),
('Inorganic Q5: p-block contains groups',
 '[{"label":"A","text":"13 to 18"},{"label":"B","text":"1 and 2"},{"label":"C","text":"3 to 12"},{"label":"D","text":"Lanthanides"}]',
 'A','p-block spans 13–18.','Chemistry','Inorganic Chemistry'),
-- Chemical Bonding
('Bonding Q2: Hybridization of carbon in ethene (C2H4) is',
 '[{"label":"A","text":"sp2"},{"label":"B","text":"sp"},{"label":"C","text":"sp3"},{"label":"D","text":"dsp2"}]',
 'A','Each carbon is sp2 hybridized.','Chemistry','Chemical Bonding'),
('Bonding Q3: VSEPR predicts H2O bond angle (~104.5°) due to',
 '[{"label":"A","text":"Lone pair repulsion"},{"label":"B","text":"No lone pairs"},{"label":"C","text":"Linear geometry"},{"label":"D","text":"Trigonal bipyramidal"}]',
 'A','Two lone pairs compress angle from 109.5°.','Chemistry','Chemical Bonding'),
('Bonding Q4: Sigma bonds are formed by',
 '[{"label":"A","text":"Head-on overlap"},{"label":"B","text":"Sidewise overlap"},{"label":"C","text":"No overlap"},{"label":"D","text":"d–d only"}]',
 'A','σ bonds result from end-to-end overlap.','Chemistry','Chemical Bonding'),
('Bonding Q5: Bond order in O2 per MO theory is',
 '[{"label":"A","text":"2"},{"label":"B","text":"1"},{"label":"C","text":"3"},{"label":"D","text":"0"}]',
 'A','(Nb − Na)/2 = (10−6)/2 = 2.','Chemistry','Chemical Bonding'),
-- Thermodynamics (Chem)
('Chem Thermo Q2: For spontaneous process at constant T,P, ΔG is',
 '[{"label":"A","text":"< 0"},{"label":"B","text":"> 0"},{"label":"C","text":"= 0 only"},{"label":"D","text":"Undefined"}]',
 'A','Negative Gibbs free energy indicates spontaneity.','Chemistry','Thermodynamics'),
('Chem Thermo Q3: Enthalpy is defined as',
 '[{"label":"A","text":"H = U + pV"},{"label":"B","text":"H = U − pV"},{"label":"C","text":"H = pV"},{"label":"D","text":"H = U/T"}]',
 'A','Definition of enthalpy.','Chemistry','Thermodynamics'),
('Chem Thermo Q4: Standard state refers to',
 '[{"label":"A","text":"1 bar pressure"},{"label":"B","text":"1 atm only"},{"label":"C","text":"0 bar"},{"label":"D","text":"Any pressure"}]',
 'A','IUPAC standard pressure is 1 bar.','Chemistry','Thermodynamics'),
('Chem Thermo Q5: Heat capacity at constant pressure vs volume',
 '[{"label":"A","text":"Cp > Cv"},{"label":"B","text":"Cp < Cv"},{"label":"C","text":"Cp = Cv"},{"label":"D","text":"No relation"}]',
 'A','Due to PV work at constant pressure.','Chemistry','Thermodynamics'),
-- Electrochemistry
('Electrochem Q2: Standard hydrogen electrode potential is',
 '[{"label":"A","text":"0 V"},{"label":"B","text":"1 V"},{"label":"C","text":"−1 V"},{"label":"D","text":"2 V"}]',
 'A','By definition 0 V.','Chemistry','Electrochemistry'),
('Electrochem Q3: Nernst equation relates cell potential to',
 '[{"label":"A","text":"Reaction quotient"},{"label":"B","text":"Temperature only"},{"label":"C","text":"Pressure only"},{"label":"D","text":"Entropy only"}]',
 'A','E = E0 − (0.0591/n) log Q at 298 K.','Chemistry','Electrochemistry'),
('Electrochem Q4: Electrolytic conduction occurs due to',
 '[{"label":"A","text":"Movement of ions"},{"label":"B","text":"Electrons only"},{"label":"C","text":"Photons"},{"label":"D","text":"Protons only"}]',
 'A','Ionic movement conducts current.','Chemistry','Electrochemistry'),
('Electrochem Q5: Faraday''s first law states mass deposited is',
 '[{"label":"A","text":"Proportional to charge passed"},{"label":"B","text":"Independent of charge"},{"label":"C","text":"Proportional to voltage"},{"label":"D","text":"Inverse of time"}]',
 'A','m ∝ It.','Chemistry','Electrochemistry'),
-- Chemical Kinetics
('Kinetics Q2: Half-life for first-order reaction is',
 '[{"label":"A","text":"0.693/k"},{"label":"B","text":"1/k"},{"label":"C","text":"k"},{"label":"D","text":"ln k"}]',
 'A','t1/2 = ln2/k.','Chemistry','Chemical Kinetics'),
('Kinetics Q3: Arrhenius equation is',
 '[{"label":"A","text":"k = A e^(−Ea/RT)"},{"label":"B","text":"k = Ae^(Ea/RT)"},{"label":"C","text":"k = E a"},{"label":"D","text":"k = 1/A"}]',
 'A','Temperature dependence of rate constant.','Chemistry','Chemical Kinetics'),
('Kinetics Q4: Catalyst affects',
 '[{"label":"A","text":"Activation energy"},{"label":"B","text":"Equilibrium constant"},{"label":"C","text":"ΔG°"},{"label":"D","text":"Stoichiometry"}]',
 'A','Ea lowered; K unchanged.','Chemistry','Chemical Kinetics'),
('Kinetics Q5: Order of reaction is determined experimentally by',
 '[{"label":"A","text":"Rate dependence on concentration"},{"label":"B","text":"Stoichiometric coefficients"},{"label":"C","text":"Color"},{"label":"D","text":"Pressure only"}]',
 'A','It is not necessarily stoichiometric.','Chemistry','Chemical Kinetics'),
-- Coordination Compounds
('Coordination Q2: EDTA is a',
 '[{"label":"A","text":"Hexadentate ligand"},{"label":"B","text":"Monodentate"},{"label":"C","text":"Bidentate"},{"label":"D","text":"Tridentate"}]',
 'A','EDTA can bind through six donor atoms.','Chemistry','Coordination Compounds'),
('Coordination Q3: The IUPAC name of [Fe(CN)6]4− is',
 '[{"label":"A","text":"Hexacyanoferrate(II)"},{"label":"B","text":"Hexacyanoferric(II)"},{"label":"C","text":"Hexacyanoferrate(III)"},{"label":"D","text":"Hexacyanoiron(0)"}]',
 'A','Fe oxidation state is +2.','Chemistry','Coordination Compounds'),
('Coordination Q4: Crystal field splitting in octahedral field gives',
 '[{"label":"A","text":"t2g and eg"},{"label":"B","text":"eg and ag"},{"label":"C","text":"t1 and t2"},{"label":"D","text":"p and d"}]',
 'A','d orbitals split into t2g (lower) and eg (higher).','Chemistry','Coordination Compounds'),
('Coordination Q5: Linkage isomerism arises due to',
 '[{"label":"A","text":"Ambidentate ligands"},{"label":"B","text":"Stereo hindrance"},{"label":"C","text":"Oxidation"},{"label":"D","text":"Hydrogen bonding"}]',
 'A','Ligands that can bind through more than one atom.','Chemistry','Coordination Compounds'),
-- P-Block Elements
('P-Block Q2: In group 15, boiling point increases',
 '[{"label":"A","text":"Down the group"},{"label":"B","text":"Up the group"},{"label":"C","text":"Randomly"},{"label":"D","text":"Remains constant"}]',
 'A','Trend generally increases with molecular mass.','Chemistry','P-Block Elements'),
('P-Block Q3: Allotropy is shown by',
 '[{"label":"A","text":"Carbon"},{"label":"B","text":"Neon"},{"label":"C","text":"Sodium"},{"label":"D","text":"Calcium"}]',
 'A','Diamond, graphite are allotropes of carbon.','Chemistry','P-Block Elements'),
('P-Block Q4: Electron gain enthalpy is most negative for',
 '[{"label":"A","text":"Chlorine"},{"label":"B","text":"Fluorine"},{"label":"C","text":"Oxygen"},{"label":"D","text":"Nitrogen"}]',
 'A','Cl has more negative EGE than F due to size.','Chemistry','P-Block Elements'),
('P-Block Q5: Inert pair effect is prominent in',
 '[{"label":"A","text":"Heavier p-block elements"},{"label":"B","text":"s-block elements"},{"label":"C","text":"d-block"},{"label":"D","text":"f-block"}]',
 'A','Seen in Tl, Pb, Bi etc.','Chemistry','P-Block Elements'),
-- S-Block Elements
('S-Block Q2: Alkaline earth metals belong to group',
 '[{"label":"A","text":"2"},{"label":"B","text":"1"},{"label":"C","text":"17"},{"label":"D","text":"18"}]',
 'A','Group 2.','Chemistry','S-Block Elements'),
('S-Block Q3: Flame test for sodium gives',
 '[{"label":"A","text":"Golden yellow"},{"label":"B","text":"Brick red"},{"label":"C","text":"Apple green"},{"label":"D","text":"Crimson"}]',
 'A','Characteristic yellow flame.','Chemistry','S-Block Elements'),
('S-Block Q4: Li has the highest hydration enthalpy among alkali metals due to',
 '[{"label":"A","text":"Small ionic size"},{"label":"B","text":"Large size"},{"label":"C","text":"High mass"},{"label":"D","text":"Low charge"}]',
 'A','Smaller ions hydrate more strongly.','Chemistry','S-Block Elements'),
('S-Block Q5: Solubility of hydroxides of alkaline earths increases',
 '[{"label":"A","text":"Down the group"},{"label":"B","text":"Up the group"},{"label":"C","text":"Randomly"},{"label":"D","text":"Decreases"}]',
 'A','From Mg(OH)2 to Ba(OH)2 solubility increases.','Chemistry','S-Block Elements'),
-- Hydrocarbons
('Hydrocarbons Q2: Alkyne general formula is',
 '[{"label":"A","text":"CnH2n−2"},{"label":"B","text":"CnH2n+2"},{"label":"C","text":"CnH2n"},{"label":"D","text":"CnHn"}]',
 'A','Triple bond unsaturated hydrocarbons.','Chemistry','Hydrocarbons'),
('Hydrocarbons Q3: Bromine water is decolorized by',
 '[{"label":"A","text":"Alkenes"},{"label":"B","text":"Alkanes"},{"label":"C","text":"Arenes only"},{"label":"D","text":"Alkanes with UV"}]',
 'A','Electrophilic addition across double bond.','Chemistry','Hydrocarbons'),
('Hydrocarbons Q4: Benzene undergoes mostly',
 '[{"label":"A","text":"Electrophilic substitution"},{"label":"B","text":"Addition"},{"label":"C","text":"Nucleophilic substitution"},{"label":"D","text":"Elimination"}]',
 'A','Aromatic ring preserved via substitution.','Chemistry','Hydrocarbons'),
('Hydrocarbons Q5: Marked stability of benzene is due to',
 '[{"label":"A","text":"Resonance"},{"label":"B","text":"Hyperconjugation only"},{"label":"C","text":"Inductive effect"},{"label":"D","text":"No delocalization"}]',
 'A','Delocalized pi system gives resonance stabilization.','Chemistry','Hydrocarbons'),
-- Alcohols & Ethers
('Alcohols Q2: Williamson ether synthesis forms ethers via',
 '[{"label":"A","text":"SN2 of alkoxide with primary halide"},{"label":"B","text":"SN1 with tertiary halide"},{"label":"C","text":"Elimination only"},{"label":"D","text":"Free radical"}]',
 'A','Alkoxide attacks primary haloalkane.','Chemistry','Alcohols & Ethers'),
('Alcohols Q3: Lucas test differentiates alcohols based on',
 '[{"label":"A","text":"Reactivity towards zinc chloride/HCl"},{"label":"B","text":"Color"},{"label":"C","text":"Odor"},{"label":"D","text":"Boiling point only"}]',
 'A','3° react fast, 2° moderate, 1° slow.','Chemistry','Alcohols & Ethers'),
('Alcohols Q4: Ether cleavage by HI gives',
 '[{"label":"A","text":"Alkyl iodides and alcohols"},{"label":"B","text":"Only alcohols"},{"label":"C","text":"Only alkenes"},{"label":"D","text":"Nothing"}]',
 'A','Strong acid cleaves C–O bonds.','Chemistry','Alcohols & Ethers'),
('Alcohols Q5: Oxidation of secondary alcohol yields',
 '[{"label":"A","text":"Ketone"},{"label":"B","text":"Aldehyde"},{"label":"C","text":"Acid directly"},{"label":"D","text":"Alkane"}]',
 'A','2° alcohols oxidize to ketones.','Chemistry','Alcohols & Ethers'),

-- MATHEMATICS
-- Algebra
('Algebra Q2: If roots of ax^2+bx+c=0 are real and distinct, discriminant is',
 '[{"label":"A","text":"> 0"},{"label":"B","text":"= 0"},{"label":"C","text":"< 0"},{"label":"D","text":"None"}]',
 'A','Real distinct roots require D>0.','Mathematics','Algebra'),
('Algebra Q3: Sum of roots equals',
 '[{"label":"A","text":"−b/a"},{"label":"B","text":"b/a"},{"label":"C","text":"c/a"},{"label":"D","text":"−c/a"}]',
 'A','From Vieta''s formulas.','Mathematics','Algebra'),
('Algebra Q4: Product of roots equals',
 '[{"label":"A","text":"c/a"},{"label":"B","text":"−b/a"},{"label":"C","text":"a/c"},{"label":"D","text":"−c/a"}]',
 'A','Vieta''s formulas.','Mathematics','Algebra'),
('Algebra Q5: |x| = a (a>0) has solutions',
 '[{"label":"A","text":"x = ±a"},{"label":"B","text":"x = a only"},{"label":"C","text":"x = −a only"},{"label":"D","text":"No solution"}]',
 'A','Absolute value definition.','Mathematics','Algebra'),
-- Trigonometry
('Trig Q2: tanθ equals',
 '[{"label":"A","text":"sinθ/cosθ"},{"label":"B","text":"cosθ/sinθ"},{"label":"C","text":"1/sinθ"},{"label":"D","text":"1/cosθ"}]',
 'A','Definition of tangent.','Mathematics','Trigonometry'),
('Trig Q3: sin(2θ) equals',
 '[{"label":"A","text":"2 sinθ cosθ"},{"label":"B","text":"sin^2θ + cos^2θ"},{"label":"C","text":"(sinθ+cosθ)^2"},{"label":"D","text":"cos^2θ − sin^2θ"}]',
 'A','Double-angle formula.','Mathematics','Trigonometry'),
('Trig Q4: cos(π/3) equals',
 '[{"label":"A","text":"1/2"},{"label":"B","text":"√3/2"},{"label":"C","text":"0"},{"label":"D","text":"1"}]',
 'A','Standard angle values.','Mathematics','Trigonometry'),
('Trig Q5: Principal value of sin^−1(1) is',
 '[{"label":"A","text":"π/2"},{"label":"B","text":"0"},{"label":"C","text":"π"},{"label":"D","text":"−π/2"}]',
 'A','Inverse sine at 1 gives π/2.','Mathematics','Trigonometry'),
-- Calculus
('Calculus Q2: ∫ x dx equals',
 '[{"label":"A","text":"x^2/2 + C"},{"label":"B","text":"x + C"},{"label":"C","text":"ln x + C"},{"label":"D","text":"2x + C"}]',
 'A','Basic integration rule.','Mathematics','Calculus'),
('Calculus Q3: d/dx (e^x) equals',
 '[{"label":"A","text":"e^x"},{"label":"B","text":"x e^x"},{"label":"C","text":"1/e^x"},{"label":"D","text":"0"}]',
 'A','Derivative of exponential.','Mathematics','Calculus'),
('Calculus Q4: If y = ln x, then dy/dx is',
 '[{"label":"A","text":"1/x"},{"label":"B","text":"x"},{"label":"C","text":"ln x"},{"label":"D","text":"x ln x"}]',
 'A','Derivative of natural log.','Mathematics','Calculus'),
('Calculus Q5: Critical points occur where',
 '[{"label":"A","text":"dy/dx = 0 or undefined"},{"label":"B","text":"dy/dx = 1"},{"label":"C","text":"y = 0"},{"label":"D","text":"x = 0"}]',
 'A','Extrema at zeros/undefined points of derivative.','Mathematics','Calculus'),
-- Coordinate Geometry
('Coordinate Q2: Slope of line joining (x1,y1),(x2,y2) is',
 '[{"label":"A","text":"(y2−y1)/(x2−x1)"},{"label":"B","text":"(x2−x1)/(y2−y1)"},{"label":"C","text":"x2−x1+y2−y1"},{"label":"D","text":"x1 y1"}]',
 'A','Definition of slope.','Mathematics','Coordinate Geometry'),
('Coordinate Q3: Equation of circle center (h,k) radius r',
 '[{"label":"A","text":"(x−h)^2+(y−k)^2=r^2"},{"label":"B","text":"x^2+y^2=r"},{"label":"C","text":"x+y=r^2"},{"label":"D","text":"x^2−y^2=r^2"}]',
 'A','Standard circle equation.','Mathematics','Coordinate Geometry'),
('Coordinate Q4: Midpoint formula is',
 '[{"label":"A","text":"((x1+x2)/2,(y1+y2)/2)"},{"label":"B","text":"(x1 x2, y1 y2)"},{"label":"C","text":"(x1−x2, y1−y2)"},{"label":"D","text":"(x1/x2, y1/y2)"}]',
 'A','Average of coordinates.','Mathematics','Coordinate Geometry'),
('Coordinate Q5: If two lines are perpendicular, product of slopes is',
 '[{"label":"A","text":"−1"},{"label":"B","text":"0"},{"label":"C","text":"1"},{"label":"D","text":"2"}]',
 'A','m1 m2 = −1.','Mathematics','Coordinate Geometry'),
-- Vectors
('Vectors Q2: a·a equals',
 '[{"label":"A","text":"|a|^2"},{"label":"B","text":"|a|"},{"label":"C","text":"0"},{"label":"D","text":"1"}]',
 'A','Dot product of vector with itself is magnitude squared.','Mathematics','Vectors'),
('Vectors Q3: Cross product a × b is',
 '[{"label":"A","text":"A vector perpendicular to plane"},{"label":"B","text":"Scalar"},{"label":"C","text":"Parallel to a"},{"label":"D","text":"Zero always"}]',
 'A','Direction via right-hand rule.','Mathematics','Vectors'),
('Vectors Q4: If a ⟂ b, then a·b equals',
 '[{"label":"A","text":"0"},{"label":"B","text":"1"},{"label":"C","text":"|a||b|"},{"label":"D","text":"−1"}]',
 'A','Orthogonal vectors have zero dot product.','Mathematics','Vectors'),
('Vectors Q5: Scalar triple product [a b c] equals',
 '[{"label":"A","text":"a·(b×c)"},{"label":"B","text":"a×(b×c)"},{"label":"C","text":"(a×b)×c"},{"label":"D","text":"a+b+c"}]',
 'A','Gives volume of parallelepiped.','Mathematics','Vectors'),
-- Probability
('Probability Q2: For mutually exclusive events, P(A ∪ B) is',
 '[{"label":"A","text":"P(A)+P(B)"},{"label":"B","text":"P(A)P(B)"},{"label":"C","text":"P(A)/P(B)"},{"label":"D","text":"P(A)−P(B)"}]',
 'A','No overlap so add probabilities.','Mathematics','Probability'),
('Probability Q3: If A subset B then P(A) is',
 '[{"label":"A","text":"≤ P(B)"},{"label":"B","text":"≥ P(B)"},{"label":"C","text":"= P(B) + 1"},{"label":"D","text":"Unrelated"}]',
 'A','Probability is monotonic.','Mathematics','Probability'),
('Probability Q4: Expected value E(X) for discrete X is',
 '[{"label":"A","text":"Σ x p(x)"},{"label":"B","text":"max x"},{"label":"C","text":"min x"},{"label":"D","text":"Σ p(x)"}]',
 'A','Weighted average of outcomes.','Mathematics','Probability'),
('Probability Q5: Variance Var(X) equals',
 '[{"label":"A","text":"E[X^2] − (E[X])^2"},{"label":"B","text":"E[X]"},{"label":"C","text":"E[X^2]"},{"label":"D","text":"(E[X])^2"}]',
 'A','Definition of variance.','Mathematics','Probability'),
-- Statistics
('Statistics Q2: Mode is',
 '[{"label":"A","text":"Most frequent value"},{"label":"B","text":"Middle value"},{"label":"C","text":"Average"},{"label":"D","text":"Range"}]',
 'A','Definition of mode.','Mathematics','Statistics'),
('Statistics Q3: Standard deviation is',
 '[{"label":"A","text":"Square root of variance"},{"label":"B","text":"Variance squared"},{"label":"C","text":"Mean"},{"label":"D","text":"Median"}]',
 'A','SD = sqrt(Var).','Mathematics','Statistics'),
('Statistics Q4: For symmetric distribution, mean, median, mode are',
 '[{"label":"A","text":"Equal"},{"label":"B","text":"Different"},{"label":"C","text":"Undefined"},{"label":"D","text":"Random"}]',
 'A','They coincide.','Mathematics','Statistics'),
('Statistics Q5: Z-score standardizes data using',
 '[{"label":"A","text":"(x − mean)/SD"},{"label":"B","text":"x/mean"},{"label":"C","text":"mean/x"},{"label":"D","text":"x − SD"}]',
 'A','Z = (x − μ)/σ.','Mathematics','Statistics'),
-- Complex Numbers
('Complex Q2: i equals',
 '[{"label":"A","text":"√(−1)"},{"label":"B","text":"√1"},{"label":"C","text":"−1"},{"label":"D","text":"0"}]',
 'A','Imaginary unit.','Mathematics','Complex Numbers'),
('Complex Q3: Conjugate of z = x+iy is',
 '[{"label":"A","text":"x − iy"},{"label":"B","text":"x + iy"},{"label":"C","text":"iy − x"},{"label":"D","text":"−x − iy"}]',
 'A','Change sign of imaginary part.','Mathematics','Complex Numbers'),
('Complex Q4: |z1 z2| equals',
 '[{"label":"A","text":"|z1||z2|"},{"label":"B","text":"|z1|+|z2|"},{"label":"C","text":"|z1|/|z2|"},{"label":"D","text":"0"}]',
 'A','Modulus is multiplicative.','Mathematics','Complex Numbers'),
('Complex Q5: Arg(z1 z2) equals',
 '[{"label":"A","text":"Arg z1 + Arg z2 (mod 2π)"},{"label":"B","text":"Arg z1 − Arg z2"},{"label":"C","text":"Arg z1"},{"label":"D","text":"Arg z2"}]',
 'A','Arguments add under multiplication.','Mathematics','Complex Numbers'),
-- Sequences & Series
('Seq Q2: Sum of GP a + ar + ar^2 + ... + ar^(n−1) equals',
 '[{"label":"A","text":"a(1 − r^n)/(1 − r)"},{"label":"B","text":"na"},{"label":"C","text":"a r^n"},{"label":"D","text":"a/(1−r) always"}]',
 'A','For r ≠ 1.','Mathematics','Sequences & Series'),
('Seq Q3: nth term of AP is',
 '[{"label":"A","text":"a + (n−1)d"},{"label":"B","text":"ar^(n−1)"},{"label":"C","text":"a/n"},{"label":"D","text":"nd"}]',
 'A','Definition of AP.','Mathematics','Sequences & Series'),
('Seq Q4: Convergence of series Σ 1/n diverges because',
 '[{"label":"A","text":"Harmonic series diverges"},{"label":"B","text":"Terms go to zero slowly"},{"label":"C","text":"Terms do not go to zero"},{"label":"D","text":"It is alternating"}]',
 'A','Classic result: harmonic divergence.','Mathematics','Sequences & Series'),
('Seq Q5: Binomial coefficient nCk equals',
 '[{"label":"A","text":"n!/(k!(n−k)!)"},{"label":"B","text":"n!/k!"},{"label":"C","text":"k!/n!"},{"label":"D","text":"n^k"}]',
 'A','Definition.','Mathematics','Sequences & Series'),
-- Matrices & Determinants
('Matrices Q2: Identity matrix I satisfies',
 '[{"label":"A","text":"AI = IA = A"},{"label":"B","text":"AI = 0"},{"label":"C","text":"IA = 0"},{"label":"D","text":"A^2 = I always"}]',
 'A','Identity is multiplicative identity.','Mathematics','Matrices & Determinants'),
('Matrices Q3: If det(A) ≠ 0, then A is',
 '[{"label":"A","text":"Invertible"},{"label":"B","text":"Singular"},{"label":"C","text":"Zero"},{"label":"D","text":"Orthogonal"}]',
 'A','Non-zero determinant implies invertible.','Mathematics','Matrices & Determinants'),
('Matrices Q4: det(A^T) equals',
 '[{"label":"A","text":"det(A)"},{"label":"B","text":"−det(A)"},{"label":"C","text":"det(A)^2"},{"label":"D","text":"1/det(A)"}]',
 'A','Determinant unchanged by transpose.','Mathematics','Matrices & Determinants'),
('Matrices Q5: (AB)^T equals',
 '[{"label":"A","text":"B^T A^T"},{"label":"B","text":"A^T B^T"},{"label":"C","text":"A B^T"},{"label":"D","text":"A^T B"}]',
 'A','Transpose reverses order.','Mathematics','Matrices & Determinants'),
-- Functions
('Functions Q2: A function is one-to-one if',
 '[{"label":"A","text":"Distinct inputs have distinct outputs"},{"label":"B","text":"Every input has an output"},{"label":"C","text":"Every output has an input"},{"label":"D","text":"It is continuous"}]',
 'A','Injection definition.','Mathematics','Functions'),
('Functions Q3: The inverse of f exists if f is',
 '[{"label":"A","text":"Bijective"},{"label":"B","text":"Injective only"},{"label":"C","text":"Surjective only"},{"label":"D","text":"Constant"}]',
 'A','Inverse function exists only for bijection.','Mathematics','Functions'),
('Functions Q4: Domain of ln(x) is',
 '[{"label":"A","text":"x > 0"},{"label":"B","text":"x ≥ 0"},{"label":"C","text":"x ≠ 0"},{"label":"D","text":"All real x"}]',
 'A','Natural log is defined for positive real x.','Mathematics','Functions'),
('Functions Q5: If f(x)=x^2, then f(−x) equals',
 '[{"label":"A","text":"f(x)"},{"label":"B","text":"−f(x)"},{"label":"C","text":"1/f(x)"},{"label":"D","text":"x"}]',
 'A','Even function property.','Mathematics','Functions'),
-- Binomial Theorem
('Binomial Q2: In (a+b)^n, number of terms is',
 '[{"label":"A","text":"n+1"},{"label":"B","text":"n"},{"label":"C","text":"2n"},{"label":"D","text":"n−1"}]',
 'A','From k=0..n inclusive.','Mathematics','Binomial Theorem'),
('Binomial Q3: Middle term(s) exist when',
 '[{"label":"A","text":"n is even: one middle; odd: two middle"},{"label":"B","text":"Always two"},{"label":"C","text":"Always one"},{"label":"D","text":"None"}]',
 'A','Based on parity of n.','Mathematics','Binomial Theorem'),
('Binomial Q4: Coefficient of x^k in (1+x)^n is',
 '[{"label":"A","text":"nCk"},{"label":"B","text":"kCn"},{"label":"C","text":"n+k"},{"label":"D","text":"n/k"}]',
 'A','Binomial coefficient.','Mathematics','Binomial Theorem'),
('Binomial Q5: (1−x)^−1 expands to',
 '[{"label":"A","text":"1 + x + x^2 + ... (|x|<1)"},{"label":"B","text":"1 − x + x^2"},{"label":"C","text":"1 + 2x"},{"label":"D","text":"Finite terms"}]',
 'A','Geometric series.','Mathematics','Binomial Theorem'),
-- Permutations & Combinations
('PnC Q2: Number of combinations of n distinct objects taken r is',
 '[{"label":"A","text":"n!/r!(n−r)!"},{"label":"B","text":"n!/(n−r)!"},{"label":"C","text":"r!/(n−r)!"},{"label":"D","text":"n^r"}]',
 'A','Definition of nCr.','Mathematics','Permutations & Combinations'),
('PnC Q3: Number of permutations of n distinct objects is',
 '[{"label":"A","text":"n!"},{"label":"B","text":"n"},{"label":"C","text":"n^2"},{"label":"D","text":"2^n"}]',
 'A','All arrangements equal n!.','Mathematics','Permutations & Combinations'),
('PnC Q4: Circular permutations of n distinct objects are',
 '[{"label":"A","text":"(n−1)!"},{"label":"B","text":"n!"},{"label":"C","text":"n!/2"},{"label":"D","text":"n^n"}]',
 'A','Fix one to remove rotation.','Mathematics','Permutations & Combinations'),
('PnC Q5: Number of ways to select r objects from n with repetition is',
 '[{"label":"A","text":"(n+r−1)C(r)"},{"label":"B","text":"nCr"},{"label":"C","text":"nPr"},{"label":"D","text":"n^r"}]',
 'A','Stars and bars formula.','Mathematics','Permutations & Combinations')
ON CONFLICT (subject, topic, question) DO NOTHING;