// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoemuymleuoaymuenxjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvZW11eW1sZXVvYXltdWVueGpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjcwMzksImV4cCI6MjA2Nzc0MzAzOX0.VJguxjXzpHgDQQM1cvbguI7lbo05Z4DyX56P8xoVp4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});